export const GET_MOVIE_SUCCESS="GET_MOVIE_SUCCESS"
export const CHANGE_VARIABLE="CHANGE_VARIABLE"
export const GO_TO_DETAİL="GO_TO_DETAİL"

export const INCREASE_PAGENUMBER="INCREASE_PAGENUMBER"
export const GET_PAGENUMBER="INCREASE_PAGENUMBER"



